name: Lint

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '/.node-version'
    - name: npm install, lint
      run: |
        npm ci
        npx eslint --max-warnings 0 src/**/*.ts
      env:
        CI: true

