name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, lint
      run: |
        npm ci
        npx eslint --max-warnings 0 src/**/*.ts
      env:
        CI: true

